### ISSUE TITLE
v2.2.0 cannot be used with Go modules

### ISSUE THREAD

**Issue by F21** [cenkalti/backoff#76]
Although there is a go.mod file in the repository, the latest version that can be used with Go modules (unless we force it to use a commit) is `v2.1.1`. This is because the tag is `v2.2.0`, but the import path is still `github.com/cenkalti/backoff`.

With go modules, once you get to `v2` and up, you need to update the import path to `github.com/cenkalti/backoff/v2` and so on.

**Comment by cenkalti** [comment]
I believe it is fixed now. I have followed the instructions here: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

I have bumped the version to v3.0.0 and set `v3` as main branch for the project.

**Comment by cenkalti** [comment]
@F21 Can you confirm please?

**Comment by F21** [comment]
@cenkalti Thanks for getting this sorted! This should fix the issue 👍

**Comment by bcmills** [comment]
Note that the `v3` release doesn't fix users on the non-`/v3` import path. You may want to branch and tag a `v2.2.1` release that is the same as `v2.2.0` but without the `go.mod` file.

**Comment by cenkalti** [comment]
@bcmills Done.
